### ISSUE TITLE
Set brightness and color for IR sensor group

### ISSUE THREAD

**Issue by Hugne** [nidayand/node-red-contrib-tradfri#19]
I want to set a schedule for the bathroom lights, low intensity warm light at night, full bright on daytime.
The group is on/off controlled by an IR sensor.

I'm pushing these parameters to the lights:
`{
    "color": "warm",
    "brightness": 50,
    "state": "off"
}`
`{
    "color": "cool",
    "brightness": 255,
    "state": "off"
}`
the 'state' parameter seem to be ignored though, the lights always come on..
I dont want the lights to go on when i make this change, is that possible?

**Comment by nidayand** [comment]
Please test with v1.1.1 that was released. Should work now.. Max brightness is 254 and not 255

**Comment by Hugne** [comment]
Nope, still the same, "state" is ignored when pushing light settings.
I am using 1.2.0 from NPM

> npm view node-red-contrib-tradfri |grep version
> npm info it worked if it ends with ok
> npm info using npm@5.0.3
> npm info using node@v8.1.3
> npm info attempt registry request try #1 at 18:35:59
> npm http request GET https://registry.npmjs.org/node-red-contrib-tradfri
> npm http 200 https://registry.npmjs.org/node-red-contrib-tradfri
>   versions:
>   version: '1.2.0',
> npm info ok
